version: '3.9'

services:
  redis:
    image: redis:7
    restart: always
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      hexocean_network:
  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      hexocean_network:

networks:
  hexocean_network:

volumes:
  cache:
