version: '3.9'

services:
  postgres:
    hostname: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - hexocean-db:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis


volumes:
  cache:
  hexocean-db:
