# Generated by Django 4.1.7 on 2023-03-10 13:36

from django.db import migrations


def init_data(apps, schema_editor):
    Size = apps.get_model("hexocean_app", "Size")

    size_200 = Size.objects.create(height=200)
    size_400 = Size.objects.create(height=400)

    Tier = apps.get_model("hexocean_app", "Tier")

    basic = Tier.objects.create(title="basic")
    basic.sizes.add(size_200)

    premium = Tier.objects.create(title="premium", full_size=True)
    premium.sizes.add(size_200, size_400)

    enterprise = Tier.objects.create(
        title="enterprise", full_size=True, is_expiration_link=True
    )
    enterprise.sizes.add(size_200, size_400)


class Migration(migrations.Migration):
    dependencies = [
        ("hexocean_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
